# --- Servidor ---
server.port=8080

# --- Base de Datos MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/tikal_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=tu_password_secreta
# Ahora que no estamos en producción no hay problema con poner una pasword aleatoria aquí
# Luego cambiaremos a una variable de entorno.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA y Hibernate ---
# IMPORTANTE: Cambiamos esto para que las ENTIDADES creen la BD
spring.jpa.hibernate.ddl-auto=update
# 'update': Crea las tablas si no existen, o las actualiza si cambias el código Java.
# 'create-drop': Borra todo al cerrar la app (útil para pruebas limpias).

# Desactivamos la carga del script SQL manual por ahora
spring.sql.init.mode=never

spring.jpa.show-sql=true
spring.application.name=api