package com.tikal.api.model.entity.enumerated;

public enum TypeOfGoal {
    CONCENTRATION,
    PLANNING_ACCURACY,
    GLOBAL_EFFECTIVENESS,
    PLANNING_ACCURACY_WITH_TASKS,
    EFFECTIVENESS_WITH_TASKS,
    EFFECTIVENESS_WITH_STREAK,
    PLANNING_AND_EFFECTIVENESS,
    ALL_PREVIOUS_TOTEMS
}
