/**
 * AI (SabidurIA) Service
 *
 * This module is responsible for handling all HTTP requests related to the 
 * artificial intelligence interactions within the application. It abstracts the 
 * fetch logic and exposes clean methods for managing chat sessions, retrieving 
 * paginated message histories, and communicating with the LLM agents.
 *
 * @module aiService
 */

import { apiCall } from "../../core/apiClient.js";

export const iaService = {
    /**
     * Get All Sessions
     *
     * Sends a GET request to retrieve all existing chat sessions for the authenticated user.
     * The sessions are typically returned ordered by their last updated timestamp.
     *
     * @async
     * @function
     * @returns {Promise<Array<Object>>} An array of session objects containing id, title, and updatedAt.
     * @throws {Error} Throws an error if the retrieval fails.
     */
    getAllSessions: async () => {
        return await apiCall("/api/ai/sessions", "GET");
    },

    /**
     * Create Empty Session
     *
     * Sends a POST request to initialize a brand new, empty chat session without sending 
     * any initial message. Useful for preparing the UI before the user starts typing.
     *
     * @async
     * @function
     * @returns {Promise<Object>} The newly created session object.
     * @throws {Error} Throws an error if the creation fails.
     */
    createEmptySession: async () => {
        return await apiCall("/api/ai/sessions", "POST");
    },

    /**
     * Get Session Messages (Paginated)
     *
     * Sends a GET request to retrieve the message history of a specific session.
     * The response is paginated to optimize rendering and token management.
     *
     * @async
     * @function
     * @param {string|number} sessionId - The unique identifier of the target chat session.
     * @param {number} [page=0] - The page number to retrieve (0-indexed).
     * @param {number} [size=20] - The number of messages per page.
     * @returns {Promise<Object>} A Pageable object containing the messages array and pagination metadata.
     * @throws {Error} Throws an error if the session does not exist or access is denied.
     */
    getSessionMessages: async (sessionId, page = 0, size = 20) => {
        // Se añaden los parámetros de paginación a la URL (page y size) que Spring Data JPA lee por defecto
        return await apiCall(`/api/ai/sessions/${sessionId}/messages?page=${page}&size=${size}`, "GET");
    },

    /**
     * Update Session Title
     *
     * Sends a PATCH request to rename a specific chat session. Typically used to give
     * contextual names to conversations based on the user's first prompt.
     *
     * @async
     * @function
     * @param {string|number} sessionId - The unique identifier of the target chat session.
     * @param {string} newTitle - The new title to assign to the session.
     * @returns {Promise<Object>} The updated session object.
     * @throws {Error} Throws an error if the update fails or the title is invalid.
     */
    updateSessionTitle: async (sessionId, newTitle) => {
        const encodedTitle = encodeURIComponent(newTitle);
        return await apiCall(`/api/ai/sessions/${sessionId}?title=${encodedTitle}`, "PATCH");
    },

    /**
     * Delete Session
     *
     * Sends a DELETE request to permanently remove a specific chat session 
     * along with its entire message history from the database.
     *
     * @async
     * @function
     * @param {string|number} sessionId - The unique identifier of the chat session to delete.
     * @returns {Promise<void>} Resolves when the session is successfully deleted.
     * @throws {Error} Throws an error if the deletion fails or the session does not exist.
     */
    deleteSession: async (sessionId) => {
        return await apiCall(`/api/ai/sessions/${sessionId}`, "DELETE");
    },

    /**
     * Send Message to Existing Session
     *
     * Sends a POST request with the user's prompt to an already established session.
     * The backend will process the message through the LLM and return the AI's response.
     *
     * @async
     * @function
     * @param {string|number} sessionId - The unique identifier of the active chat session.
     * @param {string} content - The text prompt entered by the user.
     * @returns {Promise<Object>} The message object generated by the AI agent.
     * @throws {Error} Throws an error if the LLM request fails or the session is invalid.
     */
    sendMessageToSession: async (sessionId, content) => {
        const payload = { content };
        return await apiCall(`/api/ai/sessions/${sessionId}/message`, "POST", payload);
    },

    /**
     * Send Message to New Session
     *
     * Sends a POST request to immediately start a conversation with a new prompt.
     * The backend creates the session and processes the message in a single transaction,
     * returning both the new session metadata and the AI's first response.
     *
     * @async
     * @function
     * @param {string} content - The text prompt entered by the user.
     * @returns {Promise<Object>} An object containing the new `session` metadata and the `firstAiMessage`.
     * @throws {Error} Throws an error if the creation or LLM request fails.
     */
    sendMessageToNewSession: async (content) => {
        const payload = { content };
        return await apiCall("/api/ai/sessions/new-chat", "POST", payload);
    }
};