version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: tikal-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=tikal_db
      - MYSQL_ROOT_PASSWORD=tu_password_secreta
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
